CREATE TABLE IF NOT EXISTS classifiers (
  claCode BIGINT UNSIGNED NOT NULL PRIMARY KEY,
  claName VARCHAR(255) NOT NULL,
  claToken VARCHAR(255) NOT NULL,
  claCreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  claUpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY ukClassifiersToken (claToken)
) ENGINE = InnoDB CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
