CREATE TABLE IF NOT EXISTS webhooks (
  webCode BIGINT UNSIGNED NOT NULL PRIMARY KEY,
  webStatus VARCHAR(1) NOT NULL DEFAULT 'A',
  claCode BIGINT UNSIGNED NOT NULL,
  webUrl VARCHAR(500) NOT NULL,
  webType VARCHAR(50) NOT NULL,
  webHeaders TEXT NULL,
  webFields TEXT NULL,
  webMethod VARCHAR(10) NOT NULL,
  webCreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  webUpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX ixWebhooksClaCode (claCode),
  CONSTRAINT fkWebhooksClaCode FOREIGN KEY (claCode) REFERENCES classifiers (claCode)
) ENGINE = InnoDB CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
